# NumPy Practice Notebook

This notebook contains a series of practice problems to help you understand and apply core concepts in NumPy.

---

## 🧩 1. Array Creation
**Question:** Create the following arrays using NumPy:
1. A 1D array with numbers from 0 to 9
2. A 2D array of shape (3, 3) filled with zeros
3. A 2D array of shape (2, 4) filled with ones
4. A 3x3 identity matrix


---


In [2]:
import numpy as np
arr1 = np.arange(10)
arr2 = np.zeros((3,3))
arr3 = np.ones((2,4))
arr4 = np.eye(3)

In [2]:
print(arr1)
print(arr2)
print(arr3)
print(arr4)

[0 1 2 3 4 5 6 7 8 9]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



## 🧪 2. Array Inspection
**Question:** Given a NumPy array `arr`, print:
1. Its shape
2. Its data type
3. The number of dimensions
4. The total number of elements

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

```

---


In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)

(2, 3)
int64
2
6



## 🔍 3. Indexing and Slicing
**Question:** Using the array below, do the following:
1. Slice the first two rows
2. Get the last column
3. Extract the element in the second row and third column
4. Reverse the rows

```python
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

```


In [4]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[:2])
print('--'*10)
print(arr[:,-1])
print('--'*10)
print(arr[1,2])
print('--'*10)
print(arr[::-1])

[[10 20 30]
 [40 50 60]]
--------------------
[30 60 90]
--------------------
60
--------------------
[[70 80 90]
 [40 50 60]
 [10 20 30]]



---

## 🔁 4. More Slicing Practice
**Question:**
Given the array below, extract:
1. All even numbers
2. The second and third rows
3. The last two columns
4. A subarray containing the middle 2x2 block

```python
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

```


In [5]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
mask = arr % 2 == 0
print(arr[mask])
print('--'*10)
print(arr[[1,2],])
print('--'*10)
print(arr[:,-2:])
print('--'*10)
print(arr[1:3,1:3])

[ 2  4  6  8 10 12 14 16]
--------------------
[[ 5  6  7  8]
 [ 9 10 11 12]]
--------------------
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
--------------------
[[ 6  7]
 [10 11]]



---

## ➕ 5. Arithmetic Operations
**Question:** Perform the following using NumPy arrays:
1. Add two arrays element-wise
2. Multiply two arrays element-wise
3. Raise all elements of an array to the power of 2

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

```

---


In [6]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)
print(arr1 * arr2)
print(arr1 ** 2)

[5 7 9]
[ 4 10 18]
[1 4 9]



## 📏 6. Broadcasting
**Question:** Use broadcasting to:
1. Add a 1D array to each row of a 2D array
2. Multiply each row of a 2D array by a 1D array
3. Subtract a scalar from each element in an array
4. Add a column vector to each column of a matrix

```python
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])
C = np.array([[1], [2]])

```


In [7]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([10, 20, 30])
C = np.array([[1],
              [2]])

print(A + B)
print(A * B)
print(A - 2)
print(A + C)

[[11 22 33]
 [14 25 36]]
[[ 10  40  90]
 [ 40 100 180]]
[[-1  0  1]
 [ 2  3  4]]
[[2 3 4]
 [6 7 8]]



---

## 🔁 7. More Broadcasting Practice
**Question:** Try these:
1. Add a 1D array of shape (4,) to a 2D array of shape (3,4)
2. Multiply a (3,1) column array to a (1,4) row array and observe the shape
3. Add a scalar to the entire array

```python
A = np.arange(12).reshape(3, 4)
B = np.array([100, 200, 300, 400])
C = np.array([[2], [3], [4]])

```


In [8]:
A = np.arange(12).reshape(3, 4)
B = np.array([100, 200, 300, 400])
C = np.array([[2], [3], [4]])

print(A + B)
B = B.reshape((1,4))
D = B * C
print(D)
print(D.shape)
print(A + 10)

[[100 201 302 403]
 [104 205 306 407]
 [108 209 310 411]]
[[ 200  400  600  800]
 [ 300  600  900 1200]
 [ 400  800 1200 1600]]
(3, 4)
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]



---

## 🔃 8. Reshaping and Flattening
**Question:**
1. Reshape a 1D array of 12 elements into a 3x4 matrix
2. Flatten a 2D array into a 1D array

```python
arr = np.arange(12)

```


In [2]:
arr = np.arange(12)
arr = arr.reshape(3,4)
print("Reshape to 2D")
print(arr)
print("Flatten")
print(arr.reshape(12,))
# or arr.flatten() --> take a copy of the array,
# but arr.ravel() --> take view or refernce of the array,
# i.e. any change in the ravelled array

Reshape to 2D
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatten
[ 0  1  2  3  4  5  6  7  8  9 10 11]



---

## 🔗 9. Stacking and Splitting
**Question:** Stack and split arrays:
1. Stack two (2, 2) arrays vertically and horizontally
2. reshape a (4, 4) array into array of shape (2, 8)


---


In [ ]:
a = np.array([[1,2],[4,5]])
b = np.array([[3,6],[7,8]])

# Stacking Vertically
print(np.vstack((a,b)))

# Stacking Horizontally
print(np.hstack((a,b)))

print('--'*10)

c = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]])
print(c.reshape((2,8)))

[[1 2]
 [4 5]
 [3 6]
 [7 8]]
[[1 2 3 6]
 [4 5 7 8]]
--------------------
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]



## 🧠 10. Boolean Masking
**Question:**
Given an array:
1. Select all elements > 10
2. Replace all even numbers with -1

```python
arr = np.array([[5, 10, 15], [20, 25, 30]])

```


In [ ]:
arr = np.array([[5, 10, 15], [20, 25, 30]])

print(arr[arr > 10])
print('--'*10)
print(np.where(arr%2==0,-1,arr))

[15 20 25 30]
--------------------
[[ 5 -1 15]
 [-1 25 -1]]



---

## 🧮 11. Aggregation
**Question:** Calculate:
1. Sum of all elements
2. Mean of each column
3. Max value in each row
4. Standard deviation of the array

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

```


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Sum of all elements: {arr.sum()}")
print(f"Mean of each column: {arr.mean(axis=0)}")
print(f"Max value in each row: {arr.max(axis=1)}")
print(f"Standard Deviation of the array: {arr.std():.2f}")

Sum of all elements: 21
Mean of each column: [2.5 3.5 4.5]
Max value in each row: [3 6]
Standard Deviation of the array: 1.71



---

## 🧲 12. Dot Product and Matrix Multiplication
**Question:**
1. Multiply two matrices using `np.dot`

```python
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

```


In [7]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
np.dot(A, B) # If both a and b are 2-D arrays, it is matrix multiplication,
            # but using matmul or a @ b is preferred.

array([[19, 22],
       [43, 50]])


---

## 🔢 13. Random Numbers
**Question:**
1. Generate a 2x3 array of random numbers between 0 and 1
2. Generate 10 random integers between 50 and 100



In [8]:
arr_deci = np.random.rand(2,3)
arr_int = np.random.randint(50,100, size=(10,))
print(arr_deci)
print('--'*10)
print(arr_int)

[[0.62035674 0.35756037 0.01754255]
 [0.79623129 0.79400092 0.3546731 ]]
--------------------
[91 72 75 64 53 71 57 72 58 54]



---

## 📐 14. Linear Algebra
**Question:**
1. Find the rank of a matrix
2. Compute the inverse of a matrix
3. Compute the determinant of a matrix



---


In [3]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.linalg.matrix_rank(arr)

np.int64(2)

In [7]:
arr = np.array([[1,2,3],
               [7,8,9],
               [15,19,17]])

In [8]:
np.linalg.inv(arr)

array([[-0.97222222,  0.63888889, -0.16666667],
       [ 0.44444444, -0.77777778,  0.33333333],
       [ 0.36111111,  0.30555556, -0.16666667]])

In [9]:
np.linalg.det(arr)

np.float64(36.000000000000014)


## ⭐ Bonus Challenge
**Question:**
Given a 2D array of shape (6, 6), extract all 3x3 submatrices (using slicing) and store them in a list.



In [19]:
a_2d = np.random.randint(100, size=(6,6))
print("Original 2D Array:")
print(a_2d)
#-------------------------#
submatrices = []
submatrices.append([a_2d[i:i+3, j:j+3] for i in range(4) for j in range(4)])
print(submatrices)


Original 2D Array:
[[79 22 61 20 96 90]
 [25 36 51 92 45 10]
 [51 47 58 92 44 36]
 [20 80 99 18 16 21]
 [58 14 92 88 20 43]
 [90 91 10 56 36 36]]
[[array([[79, 22, 61],
       [25, 36, 51],
       [51, 47, 58]]), array([[22, 61, 20],
       [36, 51, 92],
       [47, 58, 92]]), array([[61, 20, 96],
       [51, 92, 45],
       [58, 92, 44]]), array([[20, 96, 90],
       [92, 45, 10],
       [92, 44, 36]]), array([[25, 36, 51],
       [51, 47, 58],
       [20, 80, 99]]), array([[36, 51, 92],
       [47, 58, 92],
       [80, 99, 18]]), array([[51, 92, 45],
       [58, 92, 44],
       [99, 18, 16]]), array([[92, 45, 10],
       [92, 44, 36],
       [18, 16, 21]]), array([[51, 47, 58],
       [20, 80, 99],
       [58, 14, 92]]), array([[47, 58, 92],
       [80, 99, 18],
       [14, 92, 88]]), array([[58, 92, 44],
       [99, 18, 16],
       [92, 88, 20]]), array([[92, 44, 36],
       [18, 16, 21],
       [88, 20, 43]]), array([[20, 80, 99],
       [58, 14, 92],
       [90, 91, 10]]), array([


---

Happy coding! 🎯
